//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace X7Renappo.DigiWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DigitalizacionServicioSoap", Namespace="http://Anses.gov.ar/DigitalizacionServicios/")]
    public partial class DigitalizacionServicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GuardarEDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEDocumentosPorCodigoAnsesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEDocumentosPorCUILOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEDocumentosPorNumeroDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraerEDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraerEDocumentoDMZOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEDocumentosPorCodigoExternoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEDocumentosIdPorRutaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarEDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalcularRutaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalcularRutaSistemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarEDocumentoV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEDocumentosPorCodigoAnsesV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEDocumentosPorCUILV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEDocumentosPorNumeroDocumentoV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback TraerEDocumentoV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback TraerEDocumentoDMZV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEDocumentosPorCodigoExternoV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarEDocumentoV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerEDocumentoV3OperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarEDocumentoV3OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DigitalizacionServicio() {
            this.Url = global::X7Renappo.Properties.Settings.Default.X7Renappo_DigiWeb_DigitalizacionServicio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GuardarEDocumentoCompletedEventHandler GuardarEDocumentoCompleted;
        
        /// <remarks/>
        public event BuscarEDocumentosPorCodigoAnsesCompletedEventHandler BuscarEDocumentosPorCodigoAnsesCompleted;
        
        /// <remarks/>
        public event BuscarEDocumentosPorCUILCompletedEventHandler BuscarEDocumentosPorCUILCompleted;
        
        /// <remarks/>
        public event BuscarEDocumentosPorNumeroDocumentoCompletedEventHandler BuscarEDocumentosPorNumeroDocumentoCompleted;
        
        /// <remarks/>
        public event TraerEDocumentoCompletedEventHandler TraerEDocumentoCompleted;
        
        /// <remarks/>
        public event TraerEDocumentoDMZCompletedEventHandler TraerEDocumentoDMZCompleted;
        
        /// <remarks/>
        public event BuscarEDocumentosPorCodigoExternoCompletedEventHandler BuscarEDocumentosPorCodigoExternoCompleted;
        
        /// <remarks/>
        public event BuscarEDocumentosIdPorRutaCompletedEventHandler BuscarEDocumentosIdPorRutaCompleted;
        
        /// <remarks/>
        public event ActualizarEDocumentoCompletedEventHandler ActualizarEDocumentoCompleted;
        
        /// <remarks/>
        public event CalcularRutaCompletedEventHandler CalcularRutaCompleted;
        
        /// <remarks/>
        public event CalcularRutaSistemaCompletedEventHandler CalcularRutaSistemaCompleted;
        
        /// <remarks/>
        public event GuardarEDocumentoV2CompletedEventHandler GuardarEDocumentoV2Completed;
        
        /// <remarks/>
        public event BuscarEDocumentosPorCodigoAnsesV2CompletedEventHandler BuscarEDocumentosPorCodigoAnsesV2Completed;
        
        /// <remarks/>
        public event BuscarEDocumentosPorCUILV2CompletedEventHandler BuscarEDocumentosPorCUILV2Completed;
        
        /// <remarks/>
        public event BuscarEDocumentosPorNumeroDocumentoV2CompletedEventHandler BuscarEDocumentosPorNumeroDocumentoV2Completed;
        
        /// <remarks/>
        public event TraerEDocumentoV2CompletedEventHandler TraerEDocumentoV2Completed;
        
        /// <remarks/>
        public event TraerEDocumentoDMZV2CompletedEventHandler TraerEDocumentoDMZV2Completed;
        
        /// <remarks/>
        public event BuscarEDocumentosPorCodigoExternoV2CompletedEventHandler BuscarEDocumentosPorCodigoExternoV2Completed;
        
        /// <remarks/>
        public event ActualizarEDocumentoV2CompletedEventHandler ActualizarEDocumentoV2Completed;
        
        /// <remarks/>
        public event ObtenerEDocumentoV3CompletedEventHandler ObtenerEDocumentoV3Completed;
        
        /// <remarks/>
        public event GuardarEDocumentoV3CompletedEventHandler GuardarEDocumentoV3Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/GuardarEDocumento", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarEDocumento(EDocumento documento) {
            this.Invoke("GuardarEDocumento", new object[] {
                        documento});
        }
        
        /// <remarks/>
        public void GuardarEDocumentoAsync(EDocumento documento) {
            this.GuardarEDocumentoAsync(documento, null);
        }
        
        /// <remarks/>
        public void GuardarEDocumentoAsync(EDocumento documento, object userState) {
            if ((this.GuardarEDocumentoOperationCompleted == null)) {
                this.GuardarEDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarEDocumentoOperationCompleted);
            }
            this.InvokeAsync("GuardarEDocumento", new object[] {
                        documento}, this.GuardarEDocumentoOperationCompleted, userState);
        }
        
        private void OnGuardarEDocumentoOperationCompleted(object arg) {
            if ((this.GuardarEDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarEDocumentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/BuscarEDocumentosPorCodigoAnses", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumento[] BuscarEDocumentosPorCodigoAnses(CodigoAnses tramite, string codigoSistema) {
            object[] results = this.Invoke("BuscarEDocumentosPorCodigoAnses", new object[] {
                        tramite,
                        codigoSistema});
            return ((EDocumento[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCodigoAnsesAsync(CodigoAnses tramite, string codigoSistema) {
            this.BuscarEDocumentosPorCodigoAnsesAsync(tramite, codigoSistema, null);
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCodigoAnsesAsync(CodigoAnses tramite, string codigoSistema, object userState) {
            if ((this.BuscarEDocumentosPorCodigoAnsesOperationCompleted == null)) {
                this.BuscarEDocumentosPorCodigoAnsesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEDocumentosPorCodigoAnsesOperationCompleted);
            }
            this.InvokeAsync("BuscarEDocumentosPorCodigoAnses", new object[] {
                        tramite,
                        codigoSistema}, this.BuscarEDocumentosPorCodigoAnsesOperationCompleted, userState);
        }
        
        private void OnBuscarEDocumentosPorCodigoAnsesOperationCompleted(object arg) {
            if ((this.BuscarEDocumentosPorCodigoAnsesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEDocumentosPorCodigoAnsesCompleted(this, new BuscarEDocumentosPorCodigoAnsesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/BuscarEDocumentosPorCUIL", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumento[] BuscarEDocumentosPorCUIL(int preCUIIL, int documentoCUIL, int digito, string codigoSistema) {
            object[] results = this.Invoke("BuscarEDocumentosPorCUIL", new object[] {
                        preCUIIL,
                        documentoCUIL,
                        digito,
                        codigoSistema});
            return ((EDocumento[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCUILAsync(int preCUIIL, int documentoCUIL, int digito, string codigoSistema) {
            this.BuscarEDocumentosPorCUILAsync(preCUIIL, documentoCUIL, digito, codigoSistema, null);
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCUILAsync(int preCUIIL, int documentoCUIL, int digito, string codigoSistema, object userState) {
            if ((this.BuscarEDocumentosPorCUILOperationCompleted == null)) {
                this.BuscarEDocumentosPorCUILOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEDocumentosPorCUILOperationCompleted);
            }
            this.InvokeAsync("BuscarEDocumentosPorCUIL", new object[] {
                        preCUIIL,
                        documentoCUIL,
                        digito,
                        codigoSistema}, this.BuscarEDocumentosPorCUILOperationCompleted, userState);
        }
        
        private void OnBuscarEDocumentosPorCUILOperationCompleted(object arg) {
            if ((this.BuscarEDocumentosPorCUILCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEDocumentosPorCUILCompleted(this, new BuscarEDocumentosPorCUILCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/BuscarEDocumentosPorNumeroDocumento", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumento[] BuscarEDocumentosPorNumeroDocumento(int documentoCUIL, string codigoSistema) {
            object[] results = this.Invoke("BuscarEDocumentosPorNumeroDocumento", new object[] {
                        documentoCUIL,
                        codigoSistema});
            return ((EDocumento[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorNumeroDocumentoAsync(int documentoCUIL, string codigoSistema) {
            this.BuscarEDocumentosPorNumeroDocumentoAsync(documentoCUIL, codigoSistema, null);
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorNumeroDocumentoAsync(int documentoCUIL, string codigoSistema, object userState) {
            if ((this.BuscarEDocumentosPorNumeroDocumentoOperationCompleted == null)) {
                this.BuscarEDocumentosPorNumeroDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEDocumentosPorNumeroDocumentoOperationCompleted);
            }
            this.InvokeAsync("BuscarEDocumentosPorNumeroDocumento", new object[] {
                        documentoCUIL,
                        codigoSistema}, this.BuscarEDocumentosPorNumeroDocumentoOperationCompleted, userState);
        }
        
        private void OnBuscarEDocumentosPorNumeroDocumentoOperationCompleted(object arg) {
            if ((this.BuscarEDocumentosPorNumeroDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEDocumentosPorNumeroDocumentoCompleted(this, new BuscarEDocumentosPorNumeroDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/TraerEDocumento", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumento TraerEDocumento(System.Guid documentoId) {
            object[] results = this.Invoke("TraerEDocumento", new object[] {
                        documentoId});
            return ((EDocumento)(results[0]));
        }
        
        /// <remarks/>
        public void TraerEDocumentoAsync(System.Guid documentoId) {
            this.TraerEDocumentoAsync(documentoId, null);
        }
        
        /// <remarks/>
        public void TraerEDocumentoAsync(System.Guid documentoId, object userState) {
            if ((this.TraerEDocumentoOperationCompleted == null)) {
                this.TraerEDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraerEDocumentoOperationCompleted);
            }
            this.InvokeAsync("TraerEDocumento", new object[] {
                        documentoId}, this.TraerEDocumentoOperationCompleted, userState);
        }
        
        private void OnTraerEDocumentoOperationCompleted(object arg) {
            if ((this.TraerEDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraerEDocumentoCompleted(this, new TraerEDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/TraerEDocumentoDMZ", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumento TraerEDocumentoDMZ(System.Guid documentoId, string rutaDestino) {
            object[] results = this.Invoke("TraerEDocumentoDMZ", new object[] {
                        documentoId,
                        rutaDestino});
            return ((EDocumento)(results[0]));
        }
        
        /// <remarks/>
        public void TraerEDocumentoDMZAsync(System.Guid documentoId, string rutaDestino) {
            this.TraerEDocumentoDMZAsync(documentoId, rutaDestino, null);
        }
        
        /// <remarks/>
        public void TraerEDocumentoDMZAsync(System.Guid documentoId, string rutaDestino, object userState) {
            if ((this.TraerEDocumentoDMZOperationCompleted == null)) {
                this.TraerEDocumentoDMZOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraerEDocumentoDMZOperationCompleted);
            }
            this.InvokeAsync("TraerEDocumentoDMZ", new object[] {
                        documentoId,
                        rutaDestino}, this.TraerEDocumentoDMZOperationCompleted, userState);
        }
        
        private void OnTraerEDocumentoDMZOperationCompleted(object arg) {
            if ((this.TraerEDocumentoDMZCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraerEDocumentoDMZCompleted(this, new TraerEDocumentoDMZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/BuscarEDocumentosPorCodigoExterno", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumento[] BuscarEDocumentosPorCodigoExterno(string codigoExterno, string codigoSistema) {
            object[] results = this.Invoke("BuscarEDocumentosPorCodigoExterno", new object[] {
                        codigoExterno,
                        codigoSistema});
            return ((EDocumento[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCodigoExternoAsync(string codigoExterno, string codigoSistema) {
            this.BuscarEDocumentosPorCodigoExternoAsync(codigoExterno, codigoSistema, null);
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCodigoExternoAsync(string codigoExterno, string codigoSistema, object userState) {
            if ((this.BuscarEDocumentosPorCodigoExternoOperationCompleted == null)) {
                this.BuscarEDocumentosPorCodigoExternoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEDocumentosPorCodigoExternoOperationCompleted);
            }
            this.InvokeAsync("BuscarEDocumentosPorCodigoExterno", new object[] {
                        codigoExterno,
                        codigoSistema}, this.BuscarEDocumentosPorCodigoExternoOperationCompleted, userState);
        }
        
        private void OnBuscarEDocumentosPorCodigoExternoOperationCompleted(object arg) {
            if ((this.BuscarEDocumentosPorCodigoExternoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEDocumentosPorCodigoExternoCompleted(this, new BuscarEDocumentosPorCodigoExternoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/BuscarEDocumentosIdPorRuta", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid[] BuscarEDocumentosIdPorRuta(string ruta) {
            object[] results = this.Invoke("BuscarEDocumentosIdPorRuta", new object[] {
                        ruta});
            return ((System.Guid[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEDocumentosIdPorRutaAsync(string ruta) {
            this.BuscarEDocumentosIdPorRutaAsync(ruta, null);
        }
        
        /// <remarks/>
        public void BuscarEDocumentosIdPorRutaAsync(string ruta, object userState) {
            if ((this.BuscarEDocumentosIdPorRutaOperationCompleted == null)) {
                this.BuscarEDocumentosIdPorRutaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEDocumentosIdPorRutaOperationCompleted);
            }
            this.InvokeAsync("BuscarEDocumentosIdPorRuta", new object[] {
                        ruta}, this.BuscarEDocumentosIdPorRutaOperationCompleted, userState);
        }
        
        private void OnBuscarEDocumentosIdPorRutaOperationCompleted(object arg) {
            if ((this.BuscarEDocumentosIdPorRutaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEDocumentosIdPorRutaCompleted(this, new BuscarEDocumentosIdPorRutaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/ActualizarEDocumento", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarEDocumento(EDocumento documento) {
            this.Invoke("ActualizarEDocumento", new object[] {
                        documento});
        }
        
        /// <remarks/>
        public void ActualizarEDocumentoAsync(EDocumento documento) {
            this.ActualizarEDocumentoAsync(documento, null);
        }
        
        /// <remarks/>
        public void ActualizarEDocumentoAsync(EDocumento documento, object userState) {
            if ((this.ActualizarEDocumentoOperationCompleted == null)) {
                this.ActualizarEDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarEDocumentoOperationCompleted);
            }
            this.InvokeAsync("ActualizarEDocumento", new object[] {
                        documento}, this.ActualizarEDocumentoOperationCompleted, userState);
        }
        
        private void OnActualizarEDocumentoOperationCompleted(object arg) {
            if ((this.ActualizarEDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarEDocumentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/CalcularRuta", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalcularRuta() {
            object[] results = this.Invoke("CalcularRuta", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalcularRutaAsync() {
            this.CalcularRutaAsync(null);
        }
        
        /// <remarks/>
        public void CalcularRutaAsync(object userState) {
            if ((this.CalcularRutaOperationCompleted == null)) {
                this.CalcularRutaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcularRutaOperationCompleted);
            }
            this.InvokeAsync("CalcularRuta", new object[0], this.CalcularRutaOperationCompleted, userState);
        }
        
        private void OnCalcularRutaOperationCompleted(object arg) {
            if ((this.CalcularRutaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalcularRutaCompleted(this, new CalcularRutaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/CalcularRutaSistema", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalcularRutaSistema(string codigoSistema) {
            object[] results = this.Invoke("CalcularRutaSistema", new object[] {
                        codigoSistema});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalcularRutaSistemaAsync(string codigoSistema) {
            this.CalcularRutaSistemaAsync(codigoSistema, null);
        }
        
        /// <remarks/>
        public void CalcularRutaSistemaAsync(string codigoSistema, object userState) {
            if ((this.CalcularRutaSistemaOperationCompleted == null)) {
                this.CalcularRutaSistemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcularRutaSistemaOperationCompleted);
            }
            this.InvokeAsync("CalcularRutaSistema", new object[] {
                        codigoSistema}, this.CalcularRutaSistemaOperationCompleted, userState);
        }
        
        private void OnCalcularRutaSistemaOperationCompleted(object arg) {
            if ((this.CalcularRutaSistemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalcularRutaSistemaCompleted(this, new CalcularRutaSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/GuardarEDocumentoV2", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarEDocumentoV2(EDocumentoOriginal documento) {
            this.Invoke("GuardarEDocumentoV2", new object[] {
                        documento});
        }
        
        /// <remarks/>
        public void GuardarEDocumentoV2Async(EDocumentoOriginal documento) {
            this.GuardarEDocumentoV2Async(documento, null);
        }
        
        /// <remarks/>
        public void GuardarEDocumentoV2Async(EDocumentoOriginal documento, object userState) {
            if ((this.GuardarEDocumentoV2OperationCompleted == null)) {
                this.GuardarEDocumentoV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarEDocumentoV2OperationCompleted);
            }
            this.InvokeAsync("GuardarEDocumentoV2", new object[] {
                        documento}, this.GuardarEDocumentoV2OperationCompleted, userState);
        }
        
        private void OnGuardarEDocumentoV2OperationCompleted(object arg) {
            if ((this.GuardarEDocumentoV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarEDocumentoV2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/BuscarEDocumentosPorCodigoAnsesV2", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumentoOriginal[] BuscarEDocumentosPorCodigoAnsesV2(CodigoAnsesV2 tramite, string codigoSistema) {
            object[] results = this.Invoke("BuscarEDocumentosPorCodigoAnsesV2", new object[] {
                        tramite,
                        codigoSistema});
            return ((EDocumentoOriginal[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCodigoAnsesV2Async(CodigoAnsesV2 tramite, string codigoSistema) {
            this.BuscarEDocumentosPorCodigoAnsesV2Async(tramite, codigoSistema, null);
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCodigoAnsesV2Async(CodigoAnsesV2 tramite, string codigoSistema, object userState) {
            if ((this.BuscarEDocumentosPorCodigoAnsesV2OperationCompleted == null)) {
                this.BuscarEDocumentosPorCodigoAnsesV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEDocumentosPorCodigoAnsesV2OperationCompleted);
            }
            this.InvokeAsync("BuscarEDocumentosPorCodigoAnsesV2", new object[] {
                        tramite,
                        codigoSistema}, this.BuscarEDocumentosPorCodigoAnsesV2OperationCompleted, userState);
        }
        
        private void OnBuscarEDocumentosPorCodigoAnsesV2OperationCompleted(object arg) {
            if ((this.BuscarEDocumentosPorCodigoAnsesV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEDocumentosPorCodigoAnsesV2Completed(this, new BuscarEDocumentosPorCodigoAnsesV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/BuscarEDocumentosPorCUILV2", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumentoOriginal[] BuscarEDocumentosPorCUILV2(int preCUIIL, string documentoCUIL, int digito, string codigoSistema) {
            object[] results = this.Invoke("BuscarEDocumentosPorCUILV2", new object[] {
                        preCUIIL,
                        documentoCUIL,
                        digito,
                        codigoSistema});
            return ((EDocumentoOriginal[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCUILV2Async(int preCUIIL, string documentoCUIL, int digito, string codigoSistema) {
            this.BuscarEDocumentosPorCUILV2Async(preCUIIL, documentoCUIL, digito, codigoSistema, null);
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCUILV2Async(int preCUIIL, string documentoCUIL, int digito, string codigoSistema, object userState) {
            if ((this.BuscarEDocumentosPorCUILV2OperationCompleted == null)) {
                this.BuscarEDocumentosPorCUILV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEDocumentosPorCUILV2OperationCompleted);
            }
            this.InvokeAsync("BuscarEDocumentosPorCUILV2", new object[] {
                        preCUIIL,
                        documentoCUIL,
                        digito,
                        codigoSistema}, this.BuscarEDocumentosPorCUILV2OperationCompleted, userState);
        }
        
        private void OnBuscarEDocumentosPorCUILV2OperationCompleted(object arg) {
            if ((this.BuscarEDocumentosPorCUILV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEDocumentosPorCUILV2Completed(this, new BuscarEDocumentosPorCUILV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/BuscarEDocumentosPorNumeroDocumentoV2" +
            "", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumentoOriginal[] BuscarEDocumentosPorNumeroDocumentoV2(string documentoCUIL, string codigoSistema) {
            object[] results = this.Invoke("BuscarEDocumentosPorNumeroDocumentoV2", new object[] {
                        documentoCUIL,
                        codigoSistema});
            return ((EDocumentoOriginal[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorNumeroDocumentoV2Async(string documentoCUIL, string codigoSistema) {
            this.BuscarEDocumentosPorNumeroDocumentoV2Async(documentoCUIL, codigoSistema, null);
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorNumeroDocumentoV2Async(string documentoCUIL, string codigoSistema, object userState) {
            if ((this.BuscarEDocumentosPorNumeroDocumentoV2OperationCompleted == null)) {
                this.BuscarEDocumentosPorNumeroDocumentoV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEDocumentosPorNumeroDocumentoV2OperationCompleted);
            }
            this.InvokeAsync("BuscarEDocumentosPorNumeroDocumentoV2", new object[] {
                        documentoCUIL,
                        codigoSistema}, this.BuscarEDocumentosPorNumeroDocumentoV2OperationCompleted, userState);
        }
        
        private void OnBuscarEDocumentosPorNumeroDocumentoV2OperationCompleted(object arg) {
            if ((this.BuscarEDocumentosPorNumeroDocumentoV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEDocumentosPorNumeroDocumentoV2Completed(this, new BuscarEDocumentosPorNumeroDocumentoV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/TraerEDocumentoV2", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumentoOriginal TraerEDocumentoV2(System.Guid documentoId) {
            object[] results = this.Invoke("TraerEDocumentoV2", new object[] {
                        documentoId});
            return ((EDocumentoOriginal)(results[0]));
        }
        
        /// <remarks/>
        public void TraerEDocumentoV2Async(System.Guid documentoId) {
            this.TraerEDocumentoV2Async(documentoId, null);
        }
        
        /// <remarks/>
        public void TraerEDocumentoV2Async(System.Guid documentoId, object userState) {
            if ((this.TraerEDocumentoV2OperationCompleted == null)) {
                this.TraerEDocumentoV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraerEDocumentoV2OperationCompleted);
            }
            this.InvokeAsync("TraerEDocumentoV2", new object[] {
                        documentoId}, this.TraerEDocumentoV2OperationCompleted, userState);
        }
        
        private void OnTraerEDocumentoV2OperationCompleted(object arg) {
            if ((this.TraerEDocumentoV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraerEDocumentoV2Completed(this, new TraerEDocumentoV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/TraerEDocumentoDMZV2", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumentoOriginal TraerEDocumentoDMZV2(System.Guid documentoId, string rutaDestino) {
            object[] results = this.Invoke("TraerEDocumentoDMZV2", new object[] {
                        documentoId,
                        rutaDestino});
            return ((EDocumentoOriginal)(results[0]));
        }
        
        /// <remarks/>
        public void TraerEDocumentoDMZV2Async(System.Guid documentoId, string rutaDestino) {
            this.TraerEDocumentoDMZV2Async(documentoId, rutaDestino, null);
        }
        
        /// <remarks/>
        public void TraerEDocumentoDMZV2Async(System.Guid documentoId, string rutaDestino, object userState) {
            if ((this.TraerEDocumentoDMZV2OperationCompleted == null)) {
                this.TraerEDocumentoDMZV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraerEDocumentoDMZV2OperationCompleted);
            }
            this.InvokeAsync("TraerEDocumentoDMZV2", new object[] {
                        documentoId,
                        rutaDestino}, this.TraerEDocumentoDMZV2OperationCompleted, userState);
        }
        
        private void OnTraerEDocumentoDMZV2OperationCompleted(object arg) {
            if ((this.TraerEDocumentoDMZV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraerEDocumentoDMZV2Completed(this, new TraerEDocumentoDMZV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/BuscarEDocumentosPorCodigoExternoV2", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDocumentoOriginal[] BuscarEDocumentosPorCodigoExternoV2(string codigoExterno, string codigoSistema) {
            object[] results = this.Invoke("BuscarEDocumentosPorCodigoExternoV2", new object[] {
                        codigoExterno,
                        codigoSistema});
            return ((EDocumentoOriginal[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCodigoExternoV2Async(string codigoExterno, string codigoSistema) {
            this.BuscarEDocumentosPorCodigoExternoV2Async(codigoExterno, codigoSistema, null);
        }
        
        /// <remarks/>
        public void BuscarEDocumentosPorCodigoExternoV2Async(string codigoExterno, string codigoSistema, object userState) {
            if ((this.BuscarEDocumentosPorCodigoExternoV2OperationCompleted == null)) {
                this.BuscarEDocumentosPorCodigoExternoV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEDocumentosPorCodigoExternoV2OperationCompleted);
            }
            this.InvokeAsync("BuscarEDocumentosPorCodigoExternoV2", new object[] {
                        codigoExterno,
                        codigoSistema}, this.BuscarEDocumentosPorCodigoExternoV2OperationCompleted, userState);
        }
        
        private void OnBuscarEDocumentosPorCodigoExternoV2OperationCompleted(object arg) {
            if ((this.BuscarEDocumentosPorCodigoExternoV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEDocumentosPorCodigoExternoV2Completed(this, new BuscarEDocumentosPorCodigoExternoV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/ActualizarEDocumentoV2", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarEDocumentoV2(EDocumentoOriginal documento) {
            this.Invoke("ActualizarEDocumentoV2", new object[] {
                        documento});
        }
        
        /// <remarks/>
        public void ActualizarEDocumentoV2Async(EDocumentoOriginal documento) {
            this.ActualizarEDocumentoV2Async(documento, null);
        }
        
        /// <remarks/>
        public void ActualizarEDocumentoV2Async(EDocumentoOriginal documento, object userState) {
            if ((this.ActualizarEDocumentoV2OperationCompleted == null)) {
                this.ActualizarEDocumentoV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarEDocumentoV2OperationCompleted);
            }
            this.InvokeAsync("ActualizarEDocumentoV2", new object[] {
                        documento}, this.ActualizarEDocumentoV2OperationCompleted, userState);
        }
        
        private void OnActualizarEDocumentoV2OperationCompleted(object arg) {
            if ((this.ActualizarEDocumentoV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarEDocumentoV2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/ObtenerEDocumentoV3", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaObtenerEDocumentoV3 ObtenerEDocumentoV3(System.Guid guid) {
            object[] results = this.Invoke("ObtenerEDocumentoV3", new object[] {
                        guid});
            return ((RespuestaObtenerEDocumentoV3)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerEDocumentoV3Async(System.Guid guid) {
            this.ObtenerEDocumentoV3Async(guid, null);
        }
        
        /// <remarks/>
        public void ObtenerEDocumentoV3Async(System.Guid guid, object userState) {
            if ((this.ObtenerEDocumentoV3OperationCompleted == null)) {
                this.ObtenerEDocumentoV3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerEDocumentoV3OperationCompleted);
            }
            this.InvokeAsync("ObtenerEDocumentoV3", new object[] {
                        guid}, this.ObtenerEDocumentoV3OperationCompleted, userState);
        }
        
        private void OnObtenerEDocumentoV3OperationCompleted(object arg) {
            if ((this.ObtenerEDocumentoV3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerEDocumentoV3Completed(this, new ObtenerEDocumentoV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Anses.gov.ar/DigitalizacionServicios/GuardarEDocumentoV3", RequestNamespace="http://Anses.gov.ar/DigitalizacionServicios/", ResponseNamespace="http://Anses.gov.ar/DigitalizacionServicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaGuardarEDocumentoV3 GuardarEDocumentoV3(EDocumentoOriginal documento, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] archivo) {
            object[] results = this.Invoke("GuardarEDocumentoV3", new object[] {
                        documento,
                        archivo});
            return ((RespuestaGuardarEDocumentoV3)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarEDocumentoV3Async(EDocumentoOriginal documento, byte[] archivo) {
            this.GuardarEDocumentoV3Async(documento, archivo, null);
        }
        
        /// <remarks/>
        public void GuardarEDocumentoV3Async(EDocumentoOriginal documento, byte[] archivo, object userState) {
            if ((this.GuardarEDocumentoV3OperationCompleted == null)) {
                this.GuardarEDocumentoV3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarEDocumentoV3OperationCompleted);
            }
            this.InvokeAsync("GuardarEDocumentoV3", new object[] {
                        documento,
                        archivo}, this.GuardarEDocumentoV3OperationCompleted, userState);
        }
        
        private void OnGuardarEDocumentoV3OperationCompleted(object arg) {
            if ((this.GuardarEDocumentoV3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarEDocumentoV3Completed(this, new GuardarEDocumentoV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Anses.gov.ar/DigitalizacionServicios/")]
    public partial class EDocumento {
        
        private System.Guid idField;
        
        private string codigoSistemaField;
        
        private int tipoEDocumentoIdField;
        
        private int estadoEDocumentoIdField;
        
        private string entidadField;
        
        private System.Nullable<byte> preCuilField;
        
        private string numeroDocumentoField;
        
        private System.Nullable<byte> digitoVerificadorField;
        
        private System.Nullable<int> tipoTramiteField;
        
        private System.Nullable<int> secuenciaField;
        
        private string codigoExternoField;
        
        private string metadataField;
        
        private string tituloField;
        
        private string descripcionField;
        
        private string nombreField;
        
        private string rutaField;
        
        private System.DateTime fechaIndexacionField;
        
        private string hashField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        public int TipoEDocumentoId {
            get {
                return this.tipoEDocumentoIdField;
            }
            set {
                this.tipoEDocumentoIdField = value;
            }
        }
        
        /// <remarks/>
        public int EstadoEDocumentoId {
            get {
                return this.estadoEDocumentoIdField;
            }
            set {
                this.estadoEDocumentoIdField = value;
            }
        }
        
        /// <remarks/>
        public string Entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> PreCuil {
            get {
                return this.preCuilField;
            }
            set {
                this.preCuilField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> DigitoVerificador {
            get {
                return this.digitoVerificadorField;
            }
            set {
                this.digitoVerificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TipoTramite {
            get {
                return this.tipoTramiteField;
            }
            set {
                this.tipoTramiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoExterno {
            get {
                return this.codigoExternoField;
            }
            set {
                this.codigoExternoField = value;
            }
        }
        
        /// <remarks/>
        public string Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Ruta {
            get {
                return this.rutaField;
            }
            set {
                this.rutaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaIndexacion {
            get {
                return this.fechaIndexacionField;
            }
            set {
                this.fechaIndexacionField = value;
            }
        }
        
        /// <remarks/>
        public string Hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Anses.gov.ar/DigitalizacionServicios/")]
    public partial class RespuestaGuardarEDocumentoV3 {
        
        private System.Nullable<System.Guid> guidField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Anses.gov.ar/DigitalizacionServicios/")]
    public partial class RespuestaObtenerEDocumentoV3 {
        
        private byte[] archivoField;
        
        private EDocumentoOriginal documentoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        public EDocumentoOriginal documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Anses.gov.ar/DigitalizacionServicios/")]
    public partial class EDocumentoOriginal {
        
        private System.Guid idField;
        
        private string codigoSistemaField;
        
        private int tipoEDocumentoIdField;
        
        private int estadoEDocumentoIdField;
        
        private string entidadField;
        
        private System.Nullable<byte> preCuilField;
        
        private string numeroDocumentoField;
        
        private System.Nullable<byte> digitoVerificadorField;
        
        private System.Nullable<int> tipoTramiteField;
        
        private System.Nullable<int> secuenciaField;
        
        private string codigoExternoField;
        
        private string metadataField;
        
        private string tituloField;
        
        private string descripcionField;
        
        private string nombreField;
        
        private string rutaField;
        
        private System.DateTime fechaIndexacionField;
        
        private string hashField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        public int TipoEDocumentoId {
            get {
                return this.tipoEDocumentoIdField;
            }
            set {
                this.tipoEDocumentoIdField = value;
            }
        }
        
        /// <remarks/>
        public int EstadoEDocumentoId {
            get {
                return this.estadoEDocumentoIdField;
            }
            set {
                this.estadoEDocumentoIdField = value;
            }
        }
        
        /// <remarks/>
        public string Entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> PreCuil {
            get {
                return this.preCuilField;
            }
            set {
                this.preCuilField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> DigitoVerificador {
            get {
                return this.digitoVerificadorField;
            }
            set {
                this.digitoVerificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TipoTramite {
            get {
                return this.tipoTramiteField;
            }
            set {
                this.tipoTramiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoExterno {
            get {
                return this.codigoExternoField;
            }
            set {
                this.codigoExternoField = value;
            }
        }
        
        /// <remarks/>
        public string Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Ruta {
            get {
                return this.rutaField;
            }
            set {
                this.rutaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaIndexacion {
            get {
                return this.fechaIndexacionField;
            }
            set {
                this.fechaIndexacionField = value;
            }
        }
        
        /// <remarks/>
        public string Hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Anses.gov.ar/DigitalizacionServicios/")]
    public partial class CodigoAnsesV2 {
        
        private string entidadField;
        
        private int preCUILField;
        
        private string documentoCUILField;
        
        private int digitoVerificadorField;
        
        private int tipoTramiteField;
        
        private int secuenciaField;
        
        /// <remarks/>
        public string Entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        public int PreCUIL {
            get {
                return this.preCUILField;
            }
            set {
                this.preCUILField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentoCUIL {
            get {
                return this.documentoCUILField;
            }
            set {
                this.documentoCUILField = value;
            }
        }
        
        /// <remarks/>
        public int DigitoVerificador {
            get {
                return this.digitoVerificadorField;
            }
            set {
                this.digitoVerificadorField = value;
            }
        }
        
        /// <remarks/>
        public int TipoTramite {
            get {
                return this.tipoTramiteField;
            }
            set {
                this.tipoTramiteField = value;
            }
        }
        
        /// <remarks/>
        public int Secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Anses.gov.ar/DigitalizacionServicios/")]
    public partial class CodigoAnses {
        
        private int entidadField;
        
        private int preCUILField;
        
        private int documentoCUILField;
        
        private int digitoVerificadorField;
        
        private int tipoTramiteField;
        
        private int secuenciaField;
        
        /// <remarks/>
        public int Entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        public int PreCUIL {
            get {
                return this.preCUILField;
            }
            set {
                this.preCUILField = value;
            }
        }
        
        /// <remarks/>
        public int DocumentoCUIL {
            get {
                return this.documentoCUILField;
            }
            set {
                this.documentoCUILField = value;
            }
        }
        
        /// <remarks/>
        public int DigitoVerificador {
            get {
                return this.digitoVerificadorField;
            }
            set {
                this.digitoVerificadorField = value;
            }
        }
        
        /// <remarks/>
        public int TipoTramite {
            get {
                return this.tipoTramiteField;
            }
            set {
                this.tipoTramiteField = value;
            }
        }
        
        /// <remarks/>
        public int Secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GuardarEDocumentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarEDocumentosPorCodigoAnsesCompletedEventHandler(object sender, BuscarEDocumentosPorCodigoAnsesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEDocumentosPorCodigoAnsesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEDocumentosPorCodigoAnsesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarEDocumentosPorCUILCompletedEventHandler(object sender, BuscarEDocumentosPorCUILCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEDocumentosPorCUILCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEDocumentosPorCUILCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarEDocumentosPorNumeroDocumentoCompletedEventHandler(object sender, BuscarEDocumentosPorNumeroDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEDocumentosPorNumeroDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEDocumentosPorNumeroDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void TraerEDocumentoCompletedEventHandler(object sender, TraerEDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraerEDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraerEDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumento)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void TraerEDocumentoDMZCompletedEventHandler(object sender, TraerEDocumentoDMZCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraerEDocumentoDMZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraerEDocumentoDMZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumento Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumento)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarEDocumentosPorCodigoExternoCompletedEventHandler(object sender, BuscarEDocumentosPorCodigoExternoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEDocumentosPorCodigoExternoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEDocumentosPorCodigoExternoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarEDocumentosIdPorRutaCompletedEventHandler(object sender, BuscarEDocumentosIdPorRutaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEDocumentosIdPorRutaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEDocumentosIdPorRutaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ActualizarEDocumentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CalcularRutaCompletedEventHandler(object sender, CalcularRutaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalcularRutaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalcularRutaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CalcularRutaSistemaCompletedEventHandler(object sender, CalcularRutaSistemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalcularRutaSistemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalcularRutaSistemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GuardarEDocumentoV2CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarEDocumentosPorCodigoAnsesV2CompletedEventHandler(object sender, BuscarEDocumentosPorCodigoAnsesV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEDocumentosPorCodigoAnsesV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEDocumentosPorCodigoAnsesV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumentoOriginal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumentoOriginal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarEDocumentosPorCUILV2CompletedEventHandler(object sender, BuscarEDocumentosPorCUILV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEDocumentosPorCUILV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEDocumentosPorCUILV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumentoOriginal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumentoOriginal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarEDocumentosPorNumeroDocumentoV2CompletedEventHandler(object sender, BuscarEDocumentosPorNumeroDocumentoV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEDocumentosPorNumeroDocumentoV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEDocumentosPorNumeroDocumentoV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumentoOriginal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumentoOriginal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void TraerEDocumentoV2CompletedEventHandler(object sender, TraerEDocumentoV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraerEDocumentoV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraerEDocumentoV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumentoOriginal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumentoOriginal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void TraerEDocumentoDMZV2CompletedEventHandler(object sender, TraerEDocumentoDMZV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraerEDocumentoDMZV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraerEDocumentoDMZV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumentoOriginal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumentoOriginal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void BuscarEDocumentosPorCodigoExternoV2CompletedEventHandler(object sender, BuscarEDocumentosPorCodigoExternoV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEDocumentosPorCodigoExternoV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEDocumentosPorCodigoExternoV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDocumentoOriginal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDocumentoOriginal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ActualizarEDocumentoV2CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ObtenerEDocumentoV3CompletedEventHandler(object sender, ObtenerEDocumentoV3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerEDocumentoV3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerEDocumentoV3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaObtenerEDocumentoV3 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaObtenerEDocumentoV3)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GuardarEDocumentoV3CompletedEventHandler(object sender, GuardarEDocumentoV3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarEDocumentoV3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarEDocumentoV3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaGuardarEDocumentoV3 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaGuardarEDocumentoV3)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591